tunnel: ${CLOUDFLARED_PAYMENT_TUNNEL_ID}
credentials-file: /etc/cloudflared/${CLOUDFLARED_PAYMENT_TUNNEL_ID}.json
protocol: http2
ingress:
  - hostname: payment.ailab.engineer
    service: http://gateway:80 
  - service: http_status:404