"""Databricks settings for the recommendation API."""

import os

DATABRICKS_HOST = os.getenv("DATABRICKS_HOST", "")
DATABRICKS_HTTP_PATH = os.getenv("DATABRICKS_HTTP_PATH", "")
DATABRICKS_ACCESS_TOKEN = os.getenv("DATABRICKS_ACCESS_TOKEN") or os.getenv(
    "DATABRICKS_TOKEN", ""
)
DATABRICKS_CATALOG = os.getenv("DATABRICKS_CATALOG", os.getenv("DATABRICKS_CATALOG_NAME", ""))
DATABRICKS_SCHEMA = os.getenv("DATABRICKS_SCHEMA", os.getenv("DATABRICKS_SCHEMA_NAME", ""))

DATABRICKS_PRODUCTS_SOURCE = os.getenv("DATABRICKS_PRODUCTS_SOURCE", "")
DATABRICKS_PRODUCTS_SQL = os.getenv("DATABRICKS_PRODUCTS_SQL", "")
DATABRICKS_PRODUCTS_ID_COLUMN = os.getenv("DATABRICKS_PRODUCTS_ID_COLUMN", "product_id")
